// SPDX-License-Identifier: Apache-2.0
#include "pcbir/board_file_view.hpp"

#include "pcbir/board_snapshot.hpp"
#include "pcbir/format_error.hpp"
#include "pcbir/format_version.hpp"
#include "pcbir/serialize.hpp"

// The FlatBuffers runtime library's own convention (every flatc-generated
// header includes exactly this), even though its symbols are physically
// declared in finer-grained sub-headers that misc-include-cleaner would
// rather see named individually.
// NOLINTNEXTLINE(misc-include-cleaner)
#include <flatbuffers/flatbuffers.h>

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <span>
#include <system_error>

#ifdef _WIN32
// NOLINTNEXTLINE(misc-include-cleaner)
#include <windows.h>
#else
#include <cerrno>

#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

// Generated by build_flatbuffers() from schemas/snapshot.fbs (src/CMakeLists.txt).
#include "snapshot_generated.h"

namespace pcbir {

namespace {

namespace fbs = pcbir::fbs;

const fbs::BoardSnapshot* mapped_root(const void* mapped) {
  return fbs::GetBoardSnapshot(mapped);
}

void verify_mapped_buffer(const void* mapped, size_t size) {
  // NOLINTNEXTLINE(misc-include-cleaner)
  flatbuffers::Verifier verifier(static_cast<const uint8_t*>(mapped), size);
  if (!fbs::VerifyBoardSnapshotBuffer(verifier)) {
    throw FormatError("corrupt or malformed board snapshot file");
  }
}

} // namespace

#ifdef _WIN32

BoardFileView BoardFileView::open(const std::filesystem::path& path, VerifyPolicy policy) {
  // NOLINTNEXTLINE(misc-include-cleaner)
  HANDLE file = CreateFileW(path.c_str(),
                            GENERIC_READ,
                            FILE_SHARE_READ,
                            nullptr,
                            OPEN_EXISTING,
                            FILE_ATTRIBUTE_NORMAL,
                            nullptr);
  if (file == INVALID_HANDLE_VALUE) {
    throw std::system_error(static_cast<int>(GetLastError()),
                            std::system_category(),
                            "failed to open board file: " + path.string());
  }

  LARGE_INTEGER file_size{};
  if (GetFileSizeEx(file, &file_size) == 0) {
    const DWORD last_error = GetLastError();
    CloseHandle(file);
    throw std::system_error(static_cast<int>(last_error),
                            std::system_category(),
                            "failed to stat board file: " + path.string());
  }
  const auto size = static_cast<size_t>(file_size.QuadPart);
  if (size == 0) {
    CloseHandle(file);
    throw FormatError("board file is empty: " + path.string());
  }

  HANDLE mapping = CreateFileMappingW(file, nullptr, PAGE_READONLY, 0, 0, nullptr);
  if (mapping == nullptr) {
    const DWORD last_error = GetLastError();
    CloseHandle(file);
    throw std::system_error(static_cast<int>(last_error),
                            std::system_category(),
                            "failed to map board file: " + path.string());
  }

  void* mapped = MapViewOfFile(mapping, FILE_MAP_READ, 0, 0, 0);
  if (mapped == nullptr) {
    const DWORD last_error = GetLastError();
    CloseHandle(mapping);
    CloseHandle(file);
    throw std::system_error(static_cast<int>(last_error),
                            std::system_category(),
                            "failed to map board file: " + path.string());
  }

  if (policy == VerifyPolicy::Verify) {
    try {
      verify_mapped_buffer(mapped, size);
    } catch (...) {
      UnmapViewOfFile(mapped);
      CloseHandle(mapping);
      CloseHandle(file);
      throw;
    }
  }

  BoardFileView view;
  view.mapped_ = mapped;
  view.mapped_size_ = size;
  view.mapping_handle_ = mapping;
  view.file_handle_ = file;
  return view;
}

void BoardFileView::release() noexcept {
  if (mapped_ != nullptr) {
    UnmapViewOfFile(mapped_);
    mapped_ = nullptr;
  }
  if (mapping_handle_ != nullptr) {
    CloseHandle(mapping_handle_);
    mapping_handle_ = nullptr;
  }
  if (file_handle_ != nullptr) {
    CloseHandle(file_handle_);
    file_handle_ = nullptr;
  }
  mapped_size_ = 0;
}

BoardFileView::BoardFileView(BoardFileView&& other) noexcept
    : mapped_(other.mapped_), mapped_size_(other.mapped_size_), file_handle_(other.file_handle_),
      mapping_handle_(other.mapping_handle_) {
  other.mapped_ = nullptr;
  other.mapped_size_ = 0;
  other.file_handle_ = nullptr;
  other.mapping_handle_ = nullptr;
}

BoardFileView& BoardFileView::operator=(BoardFileView&& other) noexcept {
  if (this == &other) {
    return *this;
  }
  release();
  mapped_ = other.mapped_;
  mapped_size_ = other.mapped_size_;
  file_handle_ = other.file_handle_;
  mapping_handle_ = other.mapping_handle_;
  other.mapped_ = nullptr;
  other.mapped_size_ = 0;
  other.file_handle_ = nullptr;
  other.mapping_handle_ = nullptr;
  return *this;
}

#else // POSIX

BoardFileView BoardFileView::open(const std::filesystem::path& path, VerifyPolicy policy) {
  const int file_descriptor = ::open(path.c_str(), O_RDONLY); // NOLINT(cppcoreguidelines-*)
  if (file_descriptor < 0) {
    throw std::system_error(
        errno, std::generic_category(), "failed to open board file: " + path.string());
  }

  struct stat status {};
  if (fstat(file_descriptor, &status) != 0) {
    const int saved_errno = errno;
    ::close(file_descriptor);
    throw std::system_error(
        saved_errno, std::generic_category(), "failed to stat board file: " + path.string());
  }
  const auto size = static_cast<size_t>(status.st_size);
  if (size == 0) {
    ::close(file_descriptor);
    throw FormatError("board file is empty: " + path.string());
  }

  void* mapped = mmap(nullptr, size, PROT_READ, MAP_PRIVATE, file_descriptor, 0);
  if (mapped == MAP_FAILED) { // NOLINT(cppcoreguidelines-pro-type-cstyle-cast)
    const int saved_errno = errno;
    ::close(file_descriptor);
    throw std::system_error(
        saved_errno, std::generic_category(), "failed to mmap board file: " + path.string());
  }

  if (policy == VerifyPolicy::Verify) {
    try {
      verify_mapped_buffer(mapped, size);
    } catch (...) {
      munmap(mapped, size);
      ::close(file_descriptor);
      throw;
    }
  }

  BoardFileView view;
  view.mapped_ = mapped;
  view.mapped_size_ = size;
  view.file_descriptor_ = file_descriptor;
  return view;
}

void BoardFileView::release() noexcept {
  if (mapped_ != nullptr) {
    munmap(mapped_, mapped_size_);
    mapped_ = nullptr;
  }
  if (file_descriptor_ >= 0) {
    ::close(file_descriptor_);
    file_descriptor_ = -1;
  }
  mapped_size_ = 0;
}

BoardFileView::BoardFileView(BoardFileView&& other) noexcept
    : mapped_(other.mapped_), mapped_size_(other.mapped_size_),
      file_descriptor_(other.file_descriptor_) {
  other.mapped_ = nullptr;
  other.mapped_size_ = 0;
  other.file_descriptor_ = -1;
}

BoardFileView& BoardFileView::operator=(BoardFileView&& other) noexcept {
  if (this == &other) {
    return *this;
  }
  release();
  mapped_ = other.mapped_;
  mapped_size_ = other.mapped_size_;
  file_descriptor_ = other.file_descriptor_;
  other.mapped_ = nullptr;
  other.mapped_size_ = 0;
  other.file_descriptor_ = -1;
  return *this;
}

#endif

BoardFileView::~BoardFileView() {
  release();
}

FormatVersion BoardFileView::format_version() const {
  const fbs::FormatVersion* version = mapped_root(mapped_)->format_version();
  return FormatVersion{.major = version->major(), .minor = version->minor()};
}

size_t BoardFileView::geometry_byte_size() const {
  const auto* bytes = mapped_root(mapped_)->geometry();
  return bytes != nullptr ? bytes->size() : 0;
}

size_t BoardFileView::connectivity_byte_size() const {
  const auto* bytes = mapped_root(mapped_)->connectivity();
  return bytes != nullptr ? bytes->size() : 0;
}

size_t BoardFileView::stackup_byte_size() const {
  const auto* bytes = mapped_root(mapped_)->stackup();
  return bytes != nullptr ? bytes->size() : 0;
}

size_t BoardFileView::extension_count() const {
  const auto* extensions = mapped_root(mapped_)->extensions();
  return extensions != nullptr ? extensions->size() : 0;
}

size_t BoardFileView::passthrough_blob_count() const {
  const auto* blobs = mapped_root(mapped_)->passthrough_blobs();
  return blobs != nullptr ? blobs->size() : 0;
}

BoardSnapshot BoardFileView::materialize() const {
  return deserialize_board(
      std::span<const uint8_t>(static_cast<const uint8_t*>(mapped_), mapped_size_));
}

} // namespace pcbir
