// SPDX-License-Identifier: Apache-2.0
#include "pcbir/serialize.hpp"

#include "pcbir/board_snapshot.hpp"
#include "pcbir/connectivity/serialize.hpp"
#include "pcbir/core/entity_id.hpp"
#include "pcbir/entity_domain.hpp"
#include "pcbir/extension.hpp"
#include "pcbir/format_error.hpp"
#include "pcbir/format_version.hpp"
#include "pcbir/geometry/serialize.hpp"
#include "pcbir/passthrough_blob.hpp"
#include "pcbir/stackup/serialize.hpp"

// The FlatBuffers runtime library's own convention (every flatc-generated
// header includes exactly this), even though its symbols are physically
// declared in finer-grained sub-headers that misc-include-cleaner would
// rather see named individually.
// NOLINTNEXTLINE(misc-include-cleaner)
#include <flatbuffers/flatbuffers.h>

#include <cstdint>
#include <span>
#include <string>
#include <vector>

// Generated by build_flatbuffers() from schemas/snapshot.fbs
// (src/CMakeLists.txt). Nests schemas/geometry.fbs, schemas/connectivity.fbs,
// and schemas/stackup.fbs's own generated headers as `nested_flatbuffer`
// blob accessors -- see schemas/snapshot.fbs for why composition is done
// this way rather than field-by-field.
#include "snapshot_generated.h"

namespace pcbir {

namespace {

namespace fbs = pcbir::fbs;

// -- FormatVersion / EntityDomain ----------------------------------------

fbs::FormatVersion write_format_version(const FormatVersion& version) {
  return {version.major, version.minor};
}

FormatVersion read_format_version(const fbs::FormatVersion* version) {
  return FormatVersion{.major = version->major(), .minor = version->minor()};
}

fbs::EntityDomain write_entity_domain(EntityDomain domain) {
  if (domain == EntityDomain::Geometry) {
    return fbs::EntityDomain_Geometry;
  }
  if (domain == EntityDomain::Connectivity) {
    return fbs::EntityDomain_Connectivity;
  }
  return fbs::EntityDomain_Stackup;
}

EntityDomain read_entity_domain(fbs::EntityDomain domain) {
  if (domain == fbs::EntityDomain_Geometry) {
    return EntityDomain::Geometry;
  }
  if (domain == fbs::EntityDomain_Connectivity) {
    return EntityDomain::Connectivity;
  }
  return EntityDomain::Stackup;
}

// -- Extension / PassthroughBlob ------------------------------------------

// NOLINTNEXTLINE(misc-include-cleaner)
flatbuffers::Offset<fbs::ExtensionEntry> write_extension(flatbuffers::FlatBufferBuilder& builder,
                                                         const Extension& extension) {
  return fbs::CreateExtensionEntryDirect(builder,
                                         write_entity_domain(extension.domain),
                                         extension.entity_id.value(),
                                         extension.ext_namespace.c_str(),
                                         extension.name.c_str(),
                                         extension.version,
                                         &extension.payload);
}

Extension read_extension(const fbs::ExtensionEntry* entry) {
  return Extension{
      .domain = read_entity_domain(entry->domain()),
      .entity_id = core::EntityId{entry->entity_id()},
      .ext_namespace =
          entry->ext_namespace() != nullptr ? entry->ext_namespace()->str() : std::string(),
      .name = entry->name() != nullptr ? entry->name()->str() : std::string(),
      .version = entry->version(),
      .payload = entry->payload() != nullptr
                     ? std::vector<uint8_t>(entry->payload()->begin(), entry->payload()->end())
                     : std::vector<uint8_t>()};
}

flatbuffers::Offset<fbs::PassthroughBlobEntry>
write_passthrough_blob(flatbuffers::FlatBufferBuilder& builder, const PassthroughBlob& blob) {
  return fbs::CreatePassthroughBlobEntryDirect(builder,
                                               write_entity_domain(blob.domain),
                                               blob.entity_id.value(),
                                               blob.source_format.c_str(),
                                               &blob.data);
}

PassthroughBlob read_passthrough_blob(const fbs::PassthroughBlobEntry* entry) {
  return PassthroughBlob{
      .domain = read_entity_domain(entry->domain()),
      .entity_id = core::EntityId{entry->entity_id()},
      .source_format =
          entry->source_format() != nullptr ? entry->source_format()->str() : std::string(),
      .data = entry->data() != nullptr
                  ? std::vector<uint8_t>(entry->data()->begin(), entry->data()->end())
                  : std::vector<uint8_t>()};
}

} // namespace

std::vector<uint8_t> serialize(const BoardSnapshot& board) {
  flatbuffers::FlatBufferBuilder builder;

  // Each layer keeps serializing itself exactly as it already did in its
  // own phase (Phases 2-4); composing a board never re-derives a layer's
  // bytes, it only embeds them.
  const std::vector<uint8_t> geometry_bytes = geometry::serialize(board.geometry);
  const std::vector<uint8_t> connectivity_bytes = connectivity::serialize(board.connectivity);
  const std::vector<uint8_t> stackup_bytes = stackup::serialize(board.stackup);

  std::vector<flatbuffers::Offset<fbs::ExtensionEntry>> extensions;
  extensions.reserve(board.extensions.size());
  for (const Extension& extension : board.extensions) {
    extensions.push_back(write_extension(builder, extension));
  }

  std::vector<flatbuffers::Offset<fbs::PassthroughBlobEntry>> passthrough_blobs;
  passthrough_blobs.reserve(board.passthrough_blobs.size());
  for (const PassthroughBlob& blob : board.passthrough_blobs) {
    passthrough_blobs.push_back(write_passthrough_blob(builder, blob));
  }

  const fbs::FormatVersion format_version = write_format_version(board.format_version);
  const flatbuffers::Offset<fbs::BoardSnapshot> root =
      fbs::CreateBoardSnapshotDirect(builder,
                                     &format_version,
                                     &geometry_bytes,
                                     &connectivity_bytes,
                                     &stackup_bytes,
                                     &extensions,
                                     &passthrough_blobs);
  builder.Finish(root);

  const uint8_t* buffer_ptr = builder.GetBufferPointer();
  // GetBufferPointer()/GetSize() are a guaranteed-consistent pair from the
  // FlatBufferBuilder's own contract.
  // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-pointer-arithmetic)
  return {buffer_ptr, buffer_ptr + builder.GetSize()};
}

BoardSnapshot deserialize_board(std::span<const uint8_t> buffer) {
  // NOLINTNEXTLINE(misc-include-cleaner)
  flatbuffers::Verifier verifier(buffer.data(), buffer.size());
  if (!fbs::VerifyBoardSnapshotBuffer(verifier)) {
    throw FormatError("corrupt or malformed board snapshot buffer");
  }

  const fbs::BoardSnapshot* board = fbs::GetBoardSnapshot(buffer.data());

  // format_version, geometry, connectivity, and stackup are all
  // `(required)` in schemas/snapshot.fbs, so VerifyBoardSnapshotBuffer
  // above already guarantees every pointer dereferenced below is non-null.
  const FormatVersion format_version = read_format_version(board->format_version());
  if (format_version.major != CURRENT_FORMAT_VERSION.major) {
    throw FormatError("unsupported board snapshot format major version");
  }

  BoardSnapshot result;
  result.format_version = format_version;

  const auto* geometry_bytes = board->geometry();
  result.geometry =
      geometry::deserialize_geometry({geometry_bytes->data(), geometry_bytes->size()}).commit();

  const auto* connectivity_bytes = board->connectivity();
  result.connectivity = connectivity::deserialize_connectivity(
                            {connectivity_bytes->data(), connectivity_bytes->size()})
                            .commit();

  const auto* stackup_bytes = board->stackup();
  result.stackup =
      stackup::deserialize_stackup({stackup_bytes->data(), stackup_bytes->size()}).commit();

  if (const auto* extensions = board->extensions()) {
    result.extensions.reserve(extensions->size());
    for (const fbs::ExtensionEntry* entry : *extensions) {
      result.extensions.push_back(read_extension(entry));
    }
  }
  if (const auto* passthrough_blobs = board->passthrough_blobs()) {
    result.passthrough_blobs.reserve(passthrough_blobs->size());
    for (const fbs::PassthroughBlobEntry* entry : *passthrough_blobs) {
      result.passthrough_blobs.push_back(read_passthrough_blob(entry));
    }
  }

  return result;
}

} // namespace pcbir
