// SPDX-License-Identifier: Apache-2.0
#include "pcbir/connectivity/serialize.hpp"

#include "pcbir/connectivity/bus.hpp"
#include "pcbir/connectivity/differential_pair.hpp"
#include "pcbir/connectivity/net.hpp"
#include "pcbir/connectivity/pin.hpp"
#include "pcbir/core/entity_id.hpp"
#include "pcbir/format_error.hpp"

// The FlatBuffers runtime library's own convention (every flatc-generated
// header includes exactly this), even though its symbols are physically
// declared in finer-grained sub-headers that misc-include-cleaner would
// rather see named individually.
// NOLINTNEXTLINE(misc-include-cleaner)
#include <flatbuffers/flatbuffers.h>

#include <cstdint>
#include <span>
#include <vector>

// Generated by build_flatbuffers() from schemas/connectivity.fbs (src/CMakeLists.txt).
#include "connectivity_generated.h"

namespace pcbir::connectivity {

namespace {

namespace fbs = pcbir::connectivity::fbs;

// NOLINTNEXTLINE(misc-include-cleaner)
flatbuffers::Offset<fbs::Net> write_net(flatbuffers::FlatBufferBuilder& builder, const Net& net) {
  return fbs::CreateNetDirect(builder, net.name.c_str());
}

Net read_net(const fbs::Net* net) {
  return Net{.name = net->name() != nullptr ? net->name()->str() : std::string()};
}

flatbuffers::Offset<fbs::Pin> write_pin(flatbuffers::FlatBufferBuilder& builder, const Pin& pin) {
  return fbs::CreatePin(builder, pin.pad.value(), pin.net.value());
}

Pin read_pin(const fbs::Pin* pin) {
  return Pin{.pad = core::EntityId{pin->pad()}, .net = core::EntityId{pin->net()}};
}

flatbuffers::Offset<fbs::DifferentialPair> write_diff_pair(flatbuffers::FlatBufferBuilder& builder,
                                                           const DifferentialPair& pair) {
  return fbs::CreateDifferentialPair(builder, pair.positive_net.value(), pair.negative_net.value());
}

DifferentialPair read_diff_pair(const fbs::DifferentialPair* pair) {
  return DifferentialPair{.positive_net = core::EntityId{pair->positive_net()},
                          .negative_net = core::EntityId{pair->negative_net()}};
}

flatbuffers::Offset<fbs::Bus> write_bus(flatbuffers::FlatBufferBuilder& builder, const Bus& bus) {
  std::vector<uint64_t> members;
  members.reserve(bus.members.size());
  for (const core::EntityId& member : bus.members) {
    members.push_back(member.value());
  }
  return fbs::CreateBusDirect(builder, bus.name.c_str(), &members);
}

Bus read_bus(const fbs::Bus* bus) {
  Bus result{.name = bus->name() != nullptr ? bus->name()->str() : std::string(), .members = {}};
  if (const auto* members = bus->members()) {
    result.members.reserve(members->size());
    for (const uint64_t member : *members) {
      result.members.emplace_back(member);
    }
  }
  return result;
}

} // namespace

std::vector<uint8_t> serialize(const ConnectivitySnapshot& snapshot) {
  flatbuffers::FlatBufferBuilder builder;

  std::vector<flatbuffers::Offset<fbs::NetEntry>> nets;
  snapshot.table<Net>().for_each([&](core::EntityId id, const Net& net) {
    nets.push_back(fbs::CreateNetEntry(builder, id.value(), write_net(builder, net)));
  });

  std::vector<flatbuffers::Offset<fbs::PinEntry>> pins;
  snapshot.table<Pin>().for_each([&](core::EntityId id, const Pin& pin) {
    pins.push_back(fbs::CreatePinEntry(builder, id.value(), write_pin(builder, pin)));
  });

  std::vector<flatbuffers::Offset<fbs::DifferentialPairEntry>> diff_pairs;
  snapshot.table<DifferentialPair>().for_each([&](core::EntityId id, const DifferentialPair& pair) {
    diff_pairs.push_back(
        fbs::CreateDifferentialPairEntry(builder, id.value(), write_diff_pair(builder, pair)));
  });

  std::vector<flatbuffers::Offset<fbs::BusEntry>> buses;
  snapshot.table<Bus>().for_each([&](core::EntityId id, const Bus& bus) {
    buses.push_back(fbs::CreateBusEntry(builder, id.value(), write_bus(builder, bus)));
  });

  const flatbuffers::Offset<fbs::ConnectivitySnapshot> root =
      fbs::CreateConnectivitySnapshotDirect(builder, &nets, &pins, &diff_pairs, &buses);
  builder.Finish(root);

  const uint8_t* buffer_ptr = builder.GetBufferPointer();
  // GetBufferPointer()/GetSize() are a guaranteed-consistent pair from the
  // FlatBufferBuilder's own contract.
  // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-pointer-arithmetic)
  return {buffer_ptr, buffer_ptr + builder.GetSize()};
}

ConnectivityWorkspace deserialize_connectivity(std::span<const uint8_t> buffer) {
  // NOLINTNEXTLINE(misc-include-cleaner)
  flatbuffers::Verifier verifier(buffer.data(), buffer.size());
  if (!fbs::VerifyConnectivitySnapshotBuffer(verifier)) {
    throw FormatError("corrupt or malformed connectivity snapshot buffer");
  }

  const fbs::ConnectivitySnapshot* snapshot = fbs::GetConnectivitySnapshot(buffer.data());
  ConnectivityWorkspace workspace;

  if (const auto* nets = snapshot->nets()) {
    for (const fbs::NetEntry* entry : *nets) {
      workspace.insert_with_id(read_net(entry->value()), core::EntityId{entry->id()});
    }
  }
  if (const auto* pins = snapshot->pins()) {
    for (const fbs::PinEntry* entry : *pins) {
      workspace.insert_with_id(read_pin(entry->value()), core::EntityId{entry->id()});
    }
  }
  if (const auto* diff_pairs = snapshot->diff_pairs()) {
    for (const fbs::DifferentialPairEntry* entry : *diff_pairs) {
      workspace.insert_with_id(read_diff_pair(entry->value()), core::EntityId{entry->id()});
    }
  }
  if (const auto* buses = snapshot->buses()) {
    for (const fbs::BusEntry* entry : *buses) {
      workspace.insert_with_id(read_bus(entry->value()), core::EntityId{entry->id()});
    }
  }

  return workspace;
}

} // namespace pcbir::connectivity
