/* SPDX-License-Identifier: Apache-2.0 */
#ifndef PCBIR_PCBIR_H
#define PCBIR_PCBIR_H

/* The stable C ABI (docs/c-abi.md, docs/rfcs/0001-stable-c-abi.md): the
 * primary linkable integration surface for closed-source tools on
 * arbitrary toolchains. C++20 is an internal implementation detail behind
 * this header -- no C++ type, template, or STL container ever appears in a
 * signature here, and this header must compile as plain C.
 *
 * Conventions (see docs/rfcs/0001-stable-c-abi.md for the full rationale):
 *  - Every function returns a pcbir_status_t; PCBIR_OK (0) means success.
 *    pcbir_last_error() gives a human-readable detail string for the last
 *    non-OK call on the current thread.
 *  - Opaque types are forward-declared only; their real definitions live in
 *    a .cpp file and are never visible to a C consumer.
 *  - An entity is referenced by a small, per-entity-typed {index,
 *    generation} handle (mirroring core::Handle<Tag>), meaningful only
 *    relative to the pcbir_*_snapshot_t it was read from -- never a raw
 *    pointer, and never mixed across entity kinds (a
 *    pcbir_net_handle_t is a distinct C type from a
 *    pcbir_material_handle_t even though their layout is identical).
 *    Every entity also has a durable uint64_t EntityId, valid across a
 *    save/reload, retrievable via a `..._entity_id()` accessor and a
 *    `..._find_by_entity_id()` lookup.
 *  - A pcbir_*_snapshot_t is immutable and independently owned once
 *    obtained (e.g. via pcbir_board_geometry()): it outlives the pcbir_board_t
 *    it came from, and every `const char*` a getter returns on it stays
 *    valid for exactly that snapshot handle's lifetime. Snapshot handles
 *    are safe to read concurrently from multiple threads with no external
 *    synchronization. A pcbir_*_workspace_t is mutable, exposes no read
 *    accessors, and is not thread-safe.
 *  - Every `_load`/`_create`/`_commit` that hands back a new handle has a
 *    matching `_free`. pcbir_board_save_bytes()'s output is freed with
 *    pcbir_bytes_free().
 */

#include <stddef.h>
#include <stdint.h>

/* Generated by CMake's GenerateExportHeader (src/CMakeLists.txt) when this
 * header is consumed from within the build that produces pcbir_c_abi;
 * defines PCBIR_API to the right dllexport/dllimport/visibility attribute
 * for whichever of static/shared that build produced. Optional: a bare
 * copy of this header with no build system behind it still compiles, with
 * PCBIR_API expanding to nothing, which is correct for the static-only
 * linking this ships with today (docs/rfcs/0001-stable-c-abi.md). */
#ifdef __has_include
#if __has_include("pcbir_c_abi_export.h")
#include "pcbir_c_abi_export.h"
#endif
#endif

#ifndef PCBIR_API
#define PCBIR_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* This header is, and must remain, idiomatic C: UPPER_CASE enum constants
 * (not the project's usual C++ CamelCase), `typedef struct` (not `using`,
 * invalid outside __cplusplus), and enums sized for the widest C ABI
 * rather than the smallest C++ representation. These checks fire on every
 * declaration below for that reason, not because the code is wrong.
 * NOLINTBEGIN(readability-identifier-naming, modernize-use-using,
 * performance-enum-size, cppcoreguidelines-macro-usage) */

/* The C ABI's own compatibility class -- deliberately independent of
 * PCBIR_VERSION_MAJOR (version.h), which tracks the library's semver.
 * Bumped only for a breaking ABI change (docs/c-abi.md); never reset by an
 * unrelated library version bump. */
#define PCBIR_ABI_VERSION 1

/* ------------------------------------------------------------- status -- */

typedef int32_t pcbir_status_t;
enum {
  PCBIR_OK = 0,
  PCBIR_ERROR_INVALID_ARGUMENT = 1,
  PCBIR_ERROR_NOT_FOUND = 2,
  PCBIR_ERROR_CORRUPT_BUFFER = 3,
  PCBIR_ERROR_UNSUPPORTED_VERSION = 4,
  PCBIR_ERROR_IO = 5,
  PCBIR_ERROR_OUT_OF_MEMORY = 6,
  PCBIR_ERROR_UNKNOWN = 7,
};

/* Thread-local; valid until the next pcbir_* call on this thread; never
 * NULL (an empty string when nothing has failed yet). */
PCBIR_API const char* pcbir_last_error(void);

/* --------------------------------------------------------- opaque types */

typedef struct pcbir_board pcbir_board_t;
typedef struct pcbir_geometry_snapshot pcbir_geometry_snapshot_t;
typedef struct pcbir_connectivity_snapshot pcbir_connectivity_snapshot_t;
typedef struct pcbir_stackup_snapshot pcbir_stackup_snapshot_t;
typedef struct pcbir_connectivity_workspace pcbir_connectivity_workspace_t;
typedef struct pcbir_geometry_diagnostics pcbir_geometry_diagnostics_t;
typedef struct pcbir_connectivity_diagnostics pcbir_connectivity_diagnostics_t;
typedef struct pcbir_stackup_diagnostics pcbir_stackup_diagnostics_t;

/* --------------------------------------- per-entity-typed handle structs */

typedef struct {
  uint32_t index;
  uint32_t generation;
} pcbir_via_handle_t;

typedef struct {
  uint32_t index;
  uint32_t generation;
} pcbir_net_handle_t;

typedef struct {
  uint32_t index;
  uint32_t generation;
} pcbir_pin_handle_t;

typedef struct {
  uint32_t index;
  uint32_t generation;
} pcbir_material_handle_t;

typedef struct {
  uint32_t index;
  uint32_t generation;
} pcbir_layer_handle_t;

/* ------------------------------------------------------- closed enums -- */

typedef uint8_t pcbir_layer_kind_t;
enum {
  PCBIR_LAYER_KIND_COPPER = 0,
  PCBIR_LAYER_KIND_DIELECTRIC = 1,
  PCBIR_LAYER_KIND_EDGE_CUTS = 2,
};

/* Mirrors pcbir::geometry::DiagnosticCode (include/pcbir/geometry/diagnostics.hpp). */
typedef uint8_t pcbir_geometry_diagnostic_code_t;
enum {
  PCBIR_GEOMETRY_DIAGNOSTIC_VALID = 0,
  PCBIR_GEOMETRY_DIAGNOSTIC_INVALID_OUTLINE = 1,
  PCBIR_GEOMETRY_DIAGNOSTIC_OUTLINE_WRONG_ORIENTATION = 2,
  PCBIR_GEOMETRY_DIAGNOSTIC_INVALID_HOLE = 3,
  PCBIR_GEOMETRY_DIAGNOSTIC_HOLE_WRONG_ORIENTATION = 4,
  PCBIR_GEOMETRY_DIAGNOSTIC_HOLE_OUTSIDE_OUTLINE = 5,
  PCBIR_GEOMETRY_DIAGNOSTIC_EMPTY_PATH = 6,
  PCBIR_GEOMETRY_DIAGNOSTIC_DISCONTINUOUS_PATH = 7,
  PCBIR_GEOMETRY_DIAGNOSTIC_INVALID_ARC_SPAN = 8,
  PCBIR_GEOMETRY_DIAGNOSTIC_NON_POSITIVE_SPAN_WIDTH = 9,
  PCBIR_GEOMETRY_DIAGNOSTIC_NON_POSITIVE_DRILL_DIAMETER = 10,
  PCBIR_GEOMETRY_DIAGNOSTIC_NON_POSITIVE_FINISHED_HOLE_DIAMETER = 11,
  PCBIR_GEOMETRY_DIAGNOSTIC_NON_POSITIVE_PAD_DIAMETER = 12,
  PCBIR_GEOMETRY_DIAGNOSTIC_NON_POSITIVE_ANNULAR_RING = 13,
};

/* Mirrors pcbir::connectivity::DiagnosticCode (include/pcbir/connectivity/diagnostics.hpp). */
typedef uint8_t pcbir_connectivity_diagnostic_code_t;
enum {
  PCBIR_CONNECTIVITY_DIAGNOSTIC_VALID = 0,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_EMPTY_NET_NAME = 1,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_INVALID_PIN = 2,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_UNCONNECTED_PIN = 3,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_DANGLING_PIN_NET_REFERENCE = 4,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_DUPLICATE_PAD_ASSIGNMENT = 5,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_DEGENERATE_DIFF_PAIR = 6,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_DANGLING_DIFF_PAIR_MEMBER = 7,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_EMPTY_BUS = 8,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_DUPLICATE_BUS_MEMBER = 9,
  PCBIR_CONNECTIVITY_DIAGNOSTIC_DANGLING_BUS_MEMBER = 10,
};

/* Mirrors pcbir::stackup::DiagnosticCode (include/pcbir/stackup/diagnostics.hpp). */
typedef uint8_t pcbir_stackup_diagnostic_code_t;
enum {
  PCBIR_STACKUP_DIAGNOSTIC_VALID = 0,
  PCBIR_STACKUP_DIAGNOSTIC_EMPTY_MATERIAL_NAME = 1,
  PCBIR_STACKUP_DIAGNOSTIC_NON_POSITIVE_DIELECTRIC_CONSTANT = 2,
  PCBIR_STACKUP_DIAGNOSTIC_NEGATIVE_LOSS_TANGENT = 3,
  PCBIR_STACKUP_DIAGNOSTIC_NON_POSITIVE_LAYER_THICKNESS = 4,
  PCBIR_STACKUP_DIAGNOSTIC_NEGATIVE_LAYER_ROUGHNESS = 5,
  PCBIR_STACKUP_DIAGNOSTIC_MISSING_DIELECTRIC_MATERIAL = 6,
  PCBIR_STACKUP_DIAGNOSTIC_EMPTY_STACKUP = 7,
  PCBIR_STACKUP_DIAGNOSTIC_DUPLICATE_STACKUP_LAYER = 8,
  PCBIR_STACKUP_DIAGNOSTIC_EMPTY_IMPEDANCE_CLASS_NAME = 9,
  PCBIR_STACKUP_DIAGNOSTIC_NON_POSITIVE_IMPEDANCE_TARGET = 10,
  PCBIR_STACKUP_DIAGNOSTIC_DANGLING_STACKUP_LAYER_REFERENCE = 11,
  PCBIR_STACKUP_DIAGNOSTIC_DANGLING_LAYER_MATERIAL_REFERENCE = 12,
  PCBIR_STACKUP_DIAGNOSTIC_DANGLING_VIA_LAYER_REFERENCE = 13,
};

/* ------------------------------------------------------------- board -- */

PCBIR_API pcbir_status_t pcbir_board_load_file(const char* path, pcbir_board_t** out_board);
PCBIR_API pcbir_status_t pcbir_board_load_bytes(const uint8_t* data,
                                                size_t size,
                                                pcbir_board_t** out_board);
PCBIR_API pcbir_status_t pcbir_board_save_file(const pcbir_board_t* board, const char* path);
/* *out_data is allocated by this call; the caller must pass it to
 * pcbir_bytes_free() exactly once. */
PCBIR_API pcbir_status_t pcbir_board_save_bytes(const pcbir_board_t* board,
                                                uint8_t** out_data,
                                                size_t* out_size);
PCBIR_API void pcbir_bytes_free(uint8_t* data);
PCBIR_API void pcbir_board_free(pcbir_board_t* board);

PCBIR_API pcbir_status_t pcbir_board_format_version(const pcbir_board_t* board,
                                                    uint32_t* out_major,
                                                    uint32_t* out_minor);
PCBIR_API pcbir_status_t pcbir_board_geometry(const pcbir_board_t* board,
                                              pcbir_geometry_snapshot_t** out_snapshot);
PCBIR_API pcbir_status_t pcbir_board_connectivity(const pcbir_board_t* board,
                                                  pcbir_connectivity_snapshot_t** out_snapshot);
PCBIR_API pcbir_status_t pcbir_board_stackup(const pcbir_board_t* board,
                                             pcbir_stackup_snapshot_t** out_snapshot);

/* Copies format_version/geometry/stackup/extensions/passthrough_blobs
 * forward from `original` and substitutes `new_connectivity`, closing the
 * loop from pcbir_connectivity_workspace_commit() back to a saveable
 * board. Analogous _with_geometry/_with_stackup are deferred until those
 * layers get their own workspace exposure (docs/rfcs/0001-stable-c-abi.md). */
PCBIR_API pcbir_status_t
pcbir_board_with_connectivity(const pcbir_board_t* original,
                              const pcbir_connectivity_snapshot_t* new_connectivity,
                              pcbir_board_t** out_board);

PCBIR_API void pcbir_geometry_snapshot_free(pcbir_geometry_snapshot_t* snapshot);
PCBIR_API void pcbir_connectivity_snapshot_free(pcbir_connectivity_snapshot_t* snapshot);
PCBIR_API void pcbir_stackup_snapshot_free(pcbir_stackup_snapshot_t* snapshot);

/* ---------------------------------------------------------------- via -- */

PCBIR_API pcbir_status_t pcbir_geometry_via_count(const pcbir_geometry_snapshot_t* snapshot,
                                                  size_t* out_count);
PCBIR_API pcbir_status_t pcbir_geometry_via_at(const pcbir_geometry_snapshot_t* snapshot,
                                               size_t index,
                                               pcbir_via_handle_t* out_handle);
PCBIR_API pcbir_status_t pcbir_geometry_via_find_by_entity_id(
    const pcbir_geometry_snapshot_t* snapshot, uint64_t entity_id, pcbir_via_handle_t* out_handle);
PCBIR_API pcbir_status_t pcbir_geometry_via_entity_id(const pcbir_geometry_snapshot_t* snapshot,
                                                      pcbir_via_handle_t handle,
                                                      uint64_t* out_entity_id);
PCBIR_API pcbir_status_t pcbir_geometry_via_position(const pcbir_geometry_snapshot_t* snapshot,
                                                     pcbir_via_handle_t handle,
                                                     int64_t* out_x,
                                                     int64_t* out_y);
PCBIR_API pcbir_status_t pcbir_geometry_via_drill_diameter_nm(
    const pcbir_geometry_snapshot_t* snapshot, pcbir_via_handle_t handle, int64_t* out_value);
PCBIR_API pcbir_status_t pcbir_geometry_via_finished_hole_diameter_nm(
    const pcbir_geometry_snapshot_t* snapshot, pcbir_via_handle_t handle, int64_t* out_value);
PCBIR_API pcbir_status_t pcbir_geometry_via_pad_diameter_nm(
    const pcbir_geometry_snapshot_t* snapshot, pcbir_via_handle_t handle, int64_t* out_value);
PCBIR_API pcbir_status_t pcbir_geometry_via_annular_ring_nm(
    const pcbir_geometry_snapshot_t* snapshot, pcbir_via_handle_t handle, int64_t* out_value);
PCBIR_API pcbir_status_t
pcbir_geometry_via_start_layer_entity_id(const pcbir_geometry_snapshot_t* snapshot,
                                         pcbir_via_handle_t handle,
                                         uint64_t* out_layer_entity_id);
PCBIR_API pcbir_status_t
pcbir_geometry_via_end_layer_entity_id(const pcbir_geometry_snapshot_t* snapshot,
                                       pcbir_via_handle_t handle,
                                       uint64_t* out_layer_entity_id);

/* --------------------------------------------------- geometry diagnostics */

PCBIR_API pcbir_status_t pcbir_geometry_validate(const pcbir_geometry_snapshot_t* snapshot,
                                                 pcbir_geometry_diagnostics_t** out_diagnostics);
PCBIR_API void pcbir_geometry_diagnostics_free(pcbir_geometry_diagnostics_t* diagnostics);
PCBIR_API pcbir_status_t pcbir_geometry_diagnostics_count(
    const pcbir_geometry_diagnostics_t* diagnostics, size_t* out_count);
PCBIR_API pcbir_status_t
pcbir_geometry_diagnostics_at(const pcbir_geometry_diagnostics_t* diagnostics,
                              size_t index,
                              uint64_t* out_entity_id,
                              pcbir_geometry_diagnostic_code_t* out_code);

/* ---------------------------------------------------------------- net -- */

PCBIR_API pcbir_status_t pcbir_connectivity_net_count(const pcbir_connectivity_snapshot_t* snapshot,
                                                      size_t* out_count);
PCBIR_API pcbir_status_t pcbir_connectivity_net_at(const pcbir_connectivity_snapshot_t* snapshot,
                                                   size_t index,
                                                   pcbir_net_handle_t* out_handle);
PCBIR_API pcbir_status_t
pcbir_connectivity_net_find_by_entity_id(const pcbir_connectivity_snapshot_t* snapshot,
                                         uint64_t entity_id,
                                         pcbir_net_handle_t* out_handle);
PCBIR_API pcbir_status_t
pcbir_connectivity_net_entity_id(const pcbir_connectivity_snapshot_t* snapshot,
                                 pcbir_net_handle_t handle,
                                 uint64_t* out_entity_id);
/* *out_name points into `snapshot`'s own storage; valid for that
 * snapshot handle's lifetime, never NULL-terminated-only (out_length is
 * always set, since a Net name may legitimately be empty). */
PCBIR_API pcbir_status_t pcbir_connectivity_net_name(const pcbir_connectivity_snapshot_t* snapshot,
                                                     pcbir_net_handle_t handle,
                                                     const char** out_name,
                                                     size_t* out_length);

/* ---------------------------------------------------------------- pin -- */

PCBIR_API pcbir_status_t pcbir_connectivity_pin_count(const pcbir_connectivity_snapshot_t* snapshot,
                                                      size_t* out_count);
PCBIR_API pcbir_status_t pcbir_connectivity_pin_at(const pcbir_connectivity_snapshot_t* snapshot,
                                                   size_t index,
                                                   pcbir_pin_handle_t* out_handle);
PCBIR_API pcbir_status_t
pcbir_connectivity_pin_find_by_entity_id(const pcbir_connectivity_snapshot_t* snapshot,
                                         uint64_t entity_id,
                                         pcbir_pin_handle_t* out_handle);
PCBIR_API pcbir_status_t
pcbir_connectivity_pin_entity_id(const pcbir_connectivity_snapshot_t* snapshot,
                                 pcbir_pin_handle_t handle,
                                 uint64_t* out_entity_id);
/* 0 (null EntityId) if the Pin has no assigned pad/net -- see
 * pcbir::connectivity::DiagnosticCode::InvalidPin / UnconnectedPin. */
PCBIR_API pcbir_status_t
pcbir_connectivity_pin_pad_entity_id(const pcbir_connectivity_snapshot_t* snapshot,
                                     pcbir_pin_handle_t handle,
                                     uint64_t* out_pad_entity_id);
PCBIR_API pcbir_status_t
pcbir_connectivity_pin_net_entity_id(const pcbir_connectivity_snapshot_t* snapshot,
                                     pcbir_pin_handle_t handle,
                                     uint64_t* out_net_entity_id);

/* ----------------------------------------------- connectivity diagnostics */

PCBIR_API pcbir_status_t
pcbir_connectivity_validate(const pcbir_connectivity_snapshot_t* snapshot,
                            pcbir_connectivity_diagnostics_t** out_diagnostics);
PCBIR_API void pcbir_connectivity_diagnostics_free(pcbir_connectivity_diagnostics_t* diagnostics);
PCBIR_API pcbir_status_t pcbir_connectivity_diagnostics_count(
    const pcbir_connectivity_diagnostics_t* diagnostics, size_t* out_count);
PCBIR_API pcbir_status_t
pcbir_connectivity_diagnostics_at(const pcbir_connectivity_diagnostics_t* diagnostics,
                                  size_t index,
                                  uint64_t* out_entity_id,
                                  pcbir_connectivity_diagnostic_code_t* out_code);

/* -------------------------------------------------- connectivity workspace */

PCBIR_API pcbir_status_t
pcbir_connectivity_workspace_create(pcbir_connectivity_workspace_t** out_workspace);
PCBIR_API pcbir_status_t pcbir_connectivity_workspace_create_from_snapshot(
    const pcbir_connectivity_snapshot_t* snapshot, pcbir_connectivity_workspace_t** out_workspace);
PCBIR_API void pcbir_connectivity_workspace_free(pcbir_connectivity_workspace_t* workspace);
PCBIR_API pcbir_status_t
pcbir_connectivity_workspace_insert_net(pcbir_connectivity_workspace_t* workspace,
                                        const char* name,
                                        size_t name_length,
                                        pcbir_net_handle_t* out_handle);
/* Produces a new immutable snapshot reflecting every edit made on
 * `workspace` so far (Workspace::commit() semantics, core/workspace.hpp);
 * `workspace` remains usable afterward for further edits. */
PCBIR_API pcbir_status_t pcbir_connectivity_workspace_commit(
    pcbir_connectivity_workspace_t* workspace, pcbir_connectivity_snapshot_t** out_snapshot);

/* ---------------------------------------------------------- material -- */

PCBIR_API pcbir_status_t pcbir_stackup_material_count(const pcbir_stackup_snapshot_t* snapshot,
                                                      size_t* out_count);
PCBIR_API pcbir_status_t pcbir_stackup_material_at(const pcbir_stackup_snapshot_t* snapshot,
                                                   size_t index,
                                                   pcbir_material_handle_t* out_handle);
PCBIR_API pcbir_status_t
pcbir_stackup_material_find_by_entity_id(const pcbir_stackup_snapshot_t* snapshot,
                                         uint64_t entity_id,
                                         pcbir_material_handle_t* out_handle);
PCBIR_API pcbir_status_t pcbir_stackup_material_entity_id(const pcbir_stackup_snapshot_t* snapshot,
                                                          pcbir_material_handle_t handle,
                                                          uint64_t* out_entity_id);
PCBIR_API pcbir_status_t pcbir_stackup_material_name(const pcbir_stackup_snapshot_t* snapshot,
                                                     pcbir_material_handle_t handle,
                                                     const char** out_name,
                                                     size_t* out_length);
/* Fixed-point, true value * 1e6 (docs/format-spec.md -- Stackup encoding);
 * e.g. a dielectric constant of 4.3 reads back as 4300000. */
PCBIR_API pcbir_status_t pcbir_stackup_material_dielectric_constant_e6(
    const pcbir_stackup_snapshot_t* snapshot, pcbir_material_handle_t handle, int64_t* out_value);
PCBIR_API pcbir_status_t pcbir_stackup_material_loss_tangent_e6(
    const pcbir_stackup_snapshot_t* snapshot, pcbir_material_handle_t handle, int64_t* out_value);

/* ------------------------------------------------------------- layer -- */

PCBIR_API pcbir_status_t pcbir_stackup_layer_count(const pcbir_stackup_snapshot_t* snapshot,
                                                   size_t* out_count);
PCBIR_API pcbir_status_t pcbir_stackup_layer_at(const pcbir_stackup_snapshot_t* snapshot,
                                                size_t index,
                                                pcbir_layer_handle_t* out_handle);
PCBIR_API pcbir_status_t pcbir_stackup_layer_find_by_entity_id(
    const pcbir_stackup_snapshot_t* snapshot, uint64_t entity_id, pcbir_layer_handle_t* out_handle);
PCBIR_API pcbir_status_t pcbir_stackup_layer_entity_id(const pcbir_stackup_snapshot_t* snapshot,
                                                       pcbir_layer_handle_t handle,
                                                       uint64_t* out_entity_id);
PCBIR_API pcbir_status_t pcbir_stackup_layer_name(const pcbir_stackup_snapshot_t* snapshot,
                                                  pcbir_layer_handle_t handle,
                                                  const char** out_name,
                                                  size_t* out_length);
PCBIR_API pcbir_status_t pcbir_stackup_layer_kind(const pcbir_stackup_snapshot_t* snapshot,
                                                  pcbir_layer_handle_t handle,
                                                  pcbir_layer_kind_t* out_kind);
PCBIR_API pcbir_status_t pcbir_stackup_layer_thickness_nm(const pcbir_stackup_snapshot_t* snapshot,
                                                          pcbir_layer_handle_t handle,
                                                          int64_t* out_value);
PCBIR_API pcbir_status_t pcbir_stackup_layer_roughness_nm(const pcbir_stackup_snapshot_t* snapshot,
                                                          pcbir_layer_handle_t handle,
                                                          int64_t* out_value);
/* 0 (null EntityId) for a Copper layer, or a Dielectric layer whose
 * material reference is itself dangling -- see
 * pcbir::stackup::DiagnosticCode::MissingDielectricMaterial /
 * DanglingLayerMaterialReference. */
PCBIR_API pcbir_status_t
pcbir_stackup_layer_material_entity_id(const pcbir_stackup_snapshot_t* snapshot,
                                       pcbir_layer_handle_t handle,
                                       uint64_t* out_material_entity_id);

/* --------------------------------------------------- stackup diagnostics */

PCBIR_API pcbir_status_t pcbir_stackup_validate(const pcbir_stackup_snapshot_t* snapshot,
                                                pcbir_stackup_diagnostics_t** out_diagnostics);
PCBIR_API void pcbir_stackup_diagnostics_free(pcbir_stackup_diagnostics_t* diagnostics);
PCBIR_API pcbir_status_t
pcbir_stackup_diagnostics_count(const pcbir_stackup_diagnostics_t* diagnostics, size_t* out_count);
PCBIR_API pcbir_status_t
pcbir_stackup_diagnostics_at(const pcbir_stackup_diagnostics_t* diagnostics,
                             size_t index,
                             uint64_t* out_entity_id,
                             pcbir_stackup_diagnostic_code_t* out_code);

/* NOLINTEND(readability-identifier-naming, modernize-use-using,
 * performance-enum-size, cppcoreguidelines-macro-usage) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* PCBIR_PCBIR_H */
