// SPDX-License-Identifier: Apache-2.0
#include "pcbir/geometry/serialize.hpp"

#include "pcbir/core/entity_id.hpp"
#include "pcbir/format_error.hpp"
#include "pcbir/geometry/arc.hpp"
#include "pcbir/geometry/board_outline.hpp"
#include "pcbir/geometry/contour.hpp"
#include "pcbir/geometry/copper_pour.hpp"
#include "pcbir/geometry/drill_hit.hpp"
#include "pcbir/geometry/footprint.hpp"
#include "pcbir/geometry/keepout.hpp"
#include "pcbir/geometry/layer_ref.hpp"
#include "pcbir/geometry/mask_opening.hpp"
#include "pcbir/geometry/pad.hpp"
#include "pcbir/geometry/path.hpp"
#include "pcbir/geometry/point.hpp"
#include "pcbir/geometry/polygon.hpp"
#include "pcbir/geometry/segment.hpp"
#include "pcbir/geometry/silkscreen_graphic.hpp"
#include "pcbir/geometry/track.hpp"
#include "pcbir/geometry/via.hpp"

// The FlatBuffers runtime library's own convention (every flatc-generated
// header includes exactly this), even though its symbols are physically
// declared in finer-grained sub-headers that misc-include-cleaner would
// rather see named individually.
// NOLINTNEXTLINE(misc-include-cleaner)
#include <flatbuffers/flatbuffers.h>

#include <cstdint>
#include <span>
#include <variant>
#include <vector>

// Generated by build_flatbuffers() from schemas/geometry.fbs (src/CMakeLists.txt).
#include "geometry_generated.h"

namespace pcbir::geometry {

namespace {

namespace fbs = pcbir::geometry::fbs;

// -- Point --------------------------------------------------------------

fbs::Point write_point(const Point& point) {
  return {point.x, point.y};
}

Point read_point(const fbs::Point* point) {
  return Point{.x = point->x(), .y = point->y()};
}

// -- Segment / Arc / Span (union) ----------------------------------------

// NOLINTNEXTLINE(misc-include-cleaner)
flatbuffers::Offset<fbs::Segment> write_segment(flatbuffers::FlatBufferBuilder& builder,
                                                const Segment& segment) {
  const fbs::Point start = write_point(segment.start);
  const fbs::Point finish = write_point(segment.end);
  return fbs::CreateSegment(builder, &start, &finish);
}

Segment read_segment(const fbs::Segment* segment) {
  return Segment{.start = read_point(segment->start()), .end = read_point(segment->finish())};
}

flatbuffers::Offset<fbs::Arc> write_arc(flatbuffers::FlatBufferBuilder& builder, const Arc& arc) {
  const fbs::Point start = write_point(arc.start);
  const fbs::Point finish = write_point(arc.end);
  const fbs::Point center = write_point(arc.center);
  const auto direction = arc.direction == ArcDirection::Clockwise
                             ? fbs::ArcDirection_Clockwise
                             : fbs::ArcDirection_CounterClockwise;
  return fbs::CreateArc(builder, &start, &finish, &center, direction);
}

Arc read_arc(const fbs::Arc* arc) {
  const ArcDirection direction = arc->direction() == fbs::ArcDirection_Clockwise
                                     ? ArcDirection::Clockwise
                                     : ArcDirection::CounterClockwise;
  return Arc{.start = read_point(arc->start()),
             .end = read_point(arc->finish()),
             .center = read_point(arc->center()),
             .direction = direction};
}

struct WrittenSpan {
  fbs::Span type = fbs::Span_NONE;
  flatbuffers::Offset<void> offset;
};

WrittenSpan write_span(flatbuffers::FlatBufferBuilder& builder, const Span& span) {
  if (const auto* segment = std::get_if<Segment>(&span)) {
    return WrittenSpan{.type = fbs::Span_Segment,
                       .offset = write_segment(builder, *segment).Union()};
  }
  return WrittenSpan{.type = fbs::Span_Arc,
                     .offset = write_arc(builder, std::get<Arc>(span)).Union()};
}

Span read_span(fbs::Span type, const void* geometry) {
  if (type == fbs::Span_Arc) {
    return Span{read_arc(static_cast<const fbs::Arc*>(geometry))};
  }
  if (type == fbs::Span_Segment) {
    return Span{read_segment(static_cast<const fbs::Segment*>(geometry))};
  }
  // Span_NONE never occurs for a spans_type entry the writer above
  // produces; FlatBuffers' union verification does not reject NONE paired
  // with a present value offset (docs/format-spec.md -- Serialization
  // fuzz target), so a NONE type here means the buffer is malformed --
  // reject it rather than reinterpreting an unrelated payload as a
  // Segment.
  throw FormatError("corrupt or malformed geometry snapshot buffer: span has no type");
}

// -- WidthSpan / Path -----------------------------------------------------

flatbuffers::Offset<fbs::WidthSpan> write_width_span(flatbuffers::FlatBufferBuilder& builder,
                                                     const WidthSpan& span) {
  const WrittenSpan written = write_span(builder, span.geometry);
  return fbs::CreateWidthSpan(builder, written.type, written.offset, span.width_nm);
}

WidthSpan read_width_span(const fbs::WidthSpan* span) {
  return WidthSpan{.geometry = read_span(span->geometry_type(), span->geometry()),
                   .width_nm = span->width_nm()};
}

flatbuffers::Offset<fbs::Path> write_path(flatbuffers::FlatBufferBuilder& builder,
                                          const Path& path) {
  std::vector<flatbuffers::Offset<fbs::WidthSpan>> spans;
  spans.reserve(path.spans.size());
  for (const WidthSpan& span : path.spans) {
    spans.push_back(write_width_span(builder, span));
  }
  return fbs::CreatePathDirect(builder, &spans);
}

Path read_path(const fbs::Path* path) {
  Path result;
  if (const auto* spans = path->spans()) {
    result.spans.reserve(spans->size());
    for (const fbs::WidthSpan* span : *spans) {
      result.spans.push_back(read_width_span(span));
    }
  }
  return result;
}

// -- Contour / Polygon ----------------------------------------------------

flatbuffers::Offset<fbs::Contour> write_contour(flatbuffers::FlatBufferBuilder& builder,
                                                const Contour& contour) {
  std::vector<uint8_t> types;
  std::vector<flatbuffers::Offset<void>> offsets;
  types.reserve(contour.spans.size());
  offsets.reserve(contour.spans.size());
  for (const Span& span : contour.spans) {
    const WrittenSpan written = write_span(builder, span);
    types.push_back(static_cast<uint8_t>(written.type));
    offsets.push_back(written.offset);
  }
  return fbs::CreateContourDirect(builder, &types, &offsets);
}

Contour read_contour(const fbs::Contour* contour) {
  Contour result;
  const auto* types = contour->spans_type();
  const auto* spans = contour->spans();
  if (types != nullptr && spans != nullptr) {
    result.spans.reserve(spans->size());
    // NOLINTNEXTLINE(misc-include-cleaner)
    for (flatbuffers::uoffset_t i = 0; i < spans->size(); ++i) {
      // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-avoid-unchecked-container-access)
      result.spans.push_back(read_span(static_cast<fbs::Span>(types->Get(i)), spans->Get(i)));
    }
  }
  return result;
}

flatbuffers::Offset<fbs::Polygon> write_polygon(flatbuffers::FlatBufferBuilder& builder,
                                                const Polygon& polygon) {
  const flatbuffers::Offset<fbs::Contour> outline = write_contour(builder, polygon.outline);
  std::vector<flatbuffers::Offset<fbs::Contour>> holes;
  holes.reserve(polygon.holes.size());
  for (const Contour& hole : polygon.holes) {
    holes.push_back(write_contour(builder, hole));
  }
  return fbs::CreatePolygonDirect(builder, outline, &holes);
}

Polygon read_polygon(const fbs::Polygon* polygon) {
  Polygon result;
  result.outline = read_contour(polygon->outline());
  if (const auto* holes = polygon->holes()) {
    result.holes.reserve(holes->size());
    for (const fbs::Contour* hole : *holes) {
      result.holes.push_back(read_contour(hole));
    }
  }
  return result;
}

// -- Board entities ---------------------------------------------------

flatbuffers::Offset<fbs::Pad> write_pad(flatbuffers::FlatBufferBuilder& builder, const Pad& pad) {
  const fbs::Point position = write_point(pad.position);
  const flatbuffers::Offset<fbs::Polygon> outline = write_polygon(builder, pad.outline);
  return fbs::CreatePadDirect(
      builder, &position, outline, pad.layer.value(), pad.pad_number.c_str());
}

Pad read_pad(const fbs::Pad* pad) {
  return Pad{.position = read_point(pad->position()),
             .outline = read_polygon(pad->outline()),
             .layer = LayerRef{pad->layer()},
             .pad_number = pad->pad_number() != nullptr ? pad->pad_number()->str() : std::string()};
}

flatbuffers::Offset<fbs::Via> write_via(flatbuffers::FlatBufferBuilder& builder, const Via& via) {
  const fbs::Point position = write_point(via.position);
  return fbs::CreateViaDirect(builder,
                              &position,
                              via.drill_diameter_nm,
                              via.finished_hole_diameter_nm,
                              via.pad_diameter_nm,
                              via.start_layer.value(),
                              via.end_layer.value(),
                              via.pad_number.c_str());
}

Via read_via(const fbs::Via* via) {
  return Via{.position = read_point(via->position()),
             .drill_diameter_nm = via->drill_diameter_nm(),
             .finished_hole_diameter_nm = via->finished_hole_diameter_nm(),
             .pad_diameter_nm = via->pad_diameter_nm(),
             .start_layer = LayerRef{via->start_layer()},
             .end_layer = LayerRef{via->end_layer()},
             .pad_number = via->pad_number() != nullptr ? via->pad_number()->str() : std::string()};
}

flatbuffers::Offset<fbs::Track> write_track(flatbuffers::FlatBufferBuilder& builder,
                                            const Track& track) {
  const flatbuffers::Offset<fbs::Path> path = write_path(builder, track.path);
  return fbs::CreateTrack(builder, path, track.layer.value(), track.net.value());
}

Track read_track(const fbs::Track* track) {
  return Track{.path = read_path(track->path()),
               .layer = LayerRef{track->layer()},
               .net = core::EntityId{track->net()}};
}

flatbuffers::Offset<fbs::CopperPour> write_copper_pour(flatbuffers::FlatBufferBuilder& builder,
                                                       const CopperPour& pour) {
  const flatbuffers::Offset<fbs::Polygon> outline = write_polygon(builder, pour.outline);
  return fbs::CreateCopperPour(builder, outline, pour.layer.value(), pour.net.value());
}

CopperPour read_copper_pour(const fbs::CopperPour* pour) {
  return CopperPour{.outline = read_polygon(pour->outline()),
                    .layer = LayerRef{pour->layer()},
                    .net = core::EntityId{pour->net()}};
}

flatbuffers::Offset<fbs::Keepout> write_keepout(flatbuffers::FlatBufferBuilder& builder,
                                                const Keepout& keepout) {
  const flatbuffers::Offset<fbs::Polygon> outline = write_polygon(builder, keepout.outline);
  return fbs::CreateKeepout(builder, outline, keepout.layer.value());
}

Keepout read_keepout(const fbs::Keepout* keepout) {
  return Keepout{.outline = read_polygon(keepout->outline()), .layer = LayerRef{keepout->layer()}};
}

flatbuffers::Offset<fbs::DrillHit> write_drill_hit(flatbuffers::FlatBufferBuilder& builder,
                                                   const DrillHit& hit) {
  const fbs::Point position = write_point(hit.position);
  return fbs::CreateDrillHit(builder, &position, hit.diameter_nm, hit.plated);
}

DrillHit read_drill_hit(const fbs::DrillHit* hit) {
  return DrillHit{.position = read_point(hit->position()),
                  .diameter_nm = hit->diameter_nm(),
                  .plated = hit->plated()};
}

flatbuffers::Offset<fbs::MaskOpening> write_mask_opening(flatbuffers::FlatBufferBuilder& builder,
                                                         const MaskOpening& opening) {
  const flatbuffers::Offset<fbs::Polygon> outline = write_polygon(builder, opening.outline);
  return fbs::CreateMaskOpening(builder, outline, opening.layer.value());
}

MaskOpening read_mask_opening(const fbs::MaskOpening* opening) {
  return MaskOpening{.outline = read_polygon(opening->outline()),
                     .layer = LayerRef{opening->layer()}};
}

flatbuffers::Offset<fbs::SilkscreenGraphic>
write_silkscreen_graphic(flatbuffers::FlatBufferBuilder& builder,
                         const SilkscreenGraphic& graphic) {
  const flatbuffers::Offset<fbs::Path> path = write_path(builder, graphic.path);
  return fbs::CreateSilkscreenGraphic(builder, path, graphic.layer.value());
}

SilkscreenGraphic read_silkscreen_graphic(const fbs::SilkscreenGraphic* graphic) {
  return SilkscreenGraphic{.path = read_path(graphic->path()), .layer = LayerRef{graphic->layer()}};
}

flatbuffers::Offset<fbs::Footprint> write_footprint(flatbuffers::FlatBufferBuilder& builder,
                                                    const Footprint& footprint) {
  const fbs::Point position = write_point(footprint.position);
  const auto side =
      footprint.side == FootprintSide::Top ? fbs::FootprintSide_Top : fbs::FootprintSide_Bottom;
  std::vector<uint64_t> pads;
  pads.reserve(footprint.pads.size());
  for (const core::EntityId& pad : footprint.pads) {
    pads.push_back(pad.value());
  }
  return fbs::CreateFootprintDirect(builder,
                                    footprint.reference_designator.c_str(),
                                    footprint.value.c_str(),
                                    &position,
                                    footprint.rotation_e6,
                                    side,
                                    &pads);
}

Footprint read_footprint(const fbs::Footprint* footprint) {
  Footprint result{
      .reference_designator = footprint->reference_designator() != nullptr
                                  ? footprint->reference_designator()->str()
                                  : std::string(),
      .value = footprint->value() != nullptr ? footprint->value()->str() : std::string(),
      .position = read_point(footprint->position()),
      .rotation_e6 = footprint->rotation_e6(),
      .side = footprint->side() == fbs::FootprintSide_Bottom ? FootprintSide::Bottom
                                                             : FootprintSide::Top,
      .pads = {},
  };
  if (const auto* pads = footprint->pads()) {
    result.pads.reserve(pads->size());
    for (const uint64_t pad : *pads) {
      result.pads.emplace_back(pad);
    }
  }
  return result;
}

flatbuffers::Offset<fbs::BoardOutline> write_board_outline(flatbuffers::FlatBufferBuilder& builder,
                                                           const BoardOutline& outline) {
  const flatbuffers::Offset<fbs::Polygon> polygon = write_polygon(builder, outline.outline);
  return fbs::CreateBoardOutline(builder, polygon, outline.layer.value());
}

BoardOutline read_board_outline(const fbs::BoardOutline* outline) {
  return BoardOutline{.outline = read_polygon(outline->outline()),
                      .layer = LayerRef{outline->layer()}};
}

// Reads every entry of one component table (if present at all -- an empty
// table is legitimately absent from the buffer, not an error) into
// `workspace`, preserving each entry's original EntityId. Factored out of
// deserialize_geometry() so that function stays one call per table rather
// than one if+for block per table, which is what actually reads the
// buffer's ten independent component tables.
template <typename Entries, typename ReadFn>
void insert_entries(GeometryWorkspace& workspace, const Entries* entries, ReadFn read) {
  if (entries == nullptr) {
    return;
  }
  for (const auto* entry : *entries) {
    workspace.insert_with_id(read(entry->value()), core::EntityId{entry->id()});
  }
}

} // namespace

std::vector<uint8_t> serialize(const GeometrySnapshot& snapshot) {
  flatbuffers::FlatBufferBuilder builder;

  std::vector<flatbuffers::Offset<fbs::PadEntry>> pads;
  snapshot.table<Pad>().for_each([&](core::EntityId id, const Pad& pad) {
    pads.push_back(fbs::CreatePadEntry(builder, id.value(), write_pad(builder, pad)));
  });

  std::vector<flatbuffers::Offset<fbs::ViaEntry>> vias;
  snapshot.table<Via>().for_each([&](core::EntityId id, const Via& via) {
    vias.push_back(fbs::CreateViaEntry(builder, id.value(), write_via(builder, via)));
  });

  std::vector<flatbuffers::Offset<fbs::TrackEntry>> tracks;
  snapshot.table<Track>().for_each([&](core::EntityId id, const Track& track) {
    tracks.push_back(fbs::CreateTrackEntry(builder, id.value(), write_track(builder, track)));
  });

  std::vector<flatbuffers::Offset<fbs::CopperPourEntry>> copper_pours;
  snapshot.table<CopperPour>().for_each([&](core::EntityId id, const CopperPour& pour) {
    copper_pours.push_back(
        fbs::CreateCopperPourEntry(builder, id.value(), write_copper_pour(builder, pour)));
  });

  std::vector<flatbuffers::Offset<fbs::KeepoutEntry>> keepouts;
  snapshot.table<Keepout>().for_each([&](core::EntityId id, const Keepout& keepout) {
    keepouts.push_back(
        fbs::CreateKeepoutEntry(builder, id.value(), write_keepout(builder, keepout)));
  });

  std::vector<flatbuffers::Offset<fbs::DrillHitEntry>> drill_hits;
  snapshot.table<DrillHit>().for_each([&](core::EntityId id, const DrillHit& hit) {
    drill_hits.push_back(
        fbs::CreateDrillHitEntry(builder, id.value(), write_drill_hit(builder, hit)));
  });

  std::vector<flatbuffers::Offset<fbs::MaskOpeningEntry>> mask_openings;
  snapshot.table<MaskOpening>().for_each([&](core::EntityId id, const MaskOpening& opening) {
    mask_openings.push_back(
        fbs::CreateMaskOpeningEntry(builder, id.value(), write_mask_opening(builder, opening)));
  });

  std::vector<flatbuffers::Offset<fbs::SilkscreenGraphicEntry>> silkscreen_graphics;
  snapshot.table<SilkscreenGraphic>().for_each(
      [&](core::EntityId id, const SilkscreenGraphic& graphic) {
        silkscreen_graphics.push_back(fbs::CreateSilkscreenGraphicEntry(
            builder, id.value(), write_silkscreen_graphic(builder, graphic)));
      });

  std::vector<flatbuffers::Offset<fbs::FootprintEntry>> footprints;
  snapshot.table<Footprint>().for_each([&](core::EntityId id, const Footprint& footprint) {
    footprints.push_back(
        fbs::CreateFootprintEntry(builder, id.value(), write_footprint(builder, footprint)));
  });

  std::vector<flatbuffers::Offset<fbs::BoardOutlineEntry>> board_outlines;
  snapshot.table<BoardOutline>().for_each([&](core::EntityId id, const BoardOutline& outline) {
    board_outlines.push_back(
        fbs::CreateBoardOutlineEntry(builder, id.value(), write_board_outline(builder, outline)));
  });

  const flatbuffers::Offset<fbs::GeometrySnapshot> root =
      fbs::CreateGeometrySnapshotDirect(builder,
                                        &pads,
                                        &vias,
                                        &tracks,
                                        &copper_pours,
                                        &keepouts,
                                        &drill_hits,
                                        &mask_openings,
                                        &silkscreen_graphics,
                                        &footprints,
                                        &board_outlines);
  builder.Finish(root);

  const uint8_t* buffer_ptr = builder.GetBufferPointer();
  // GetBufferPointer()/GetSize() are a guaranteed-consistent pair from the
  // FlatBufferBuilder's own contract.
  // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-pointer-arithmetic)
  return {buffer_ptr, buffer_ptr + builder.GetSize()};
}

GeometryWorkspace deserialize_geometry(std::span<const uint8_t> buffer) {
  // NOLINTNEXTLINE(misc-include-cleaner)
  flatbuffers::Verifier verifier(buffer.data(), buffer.size());
  if (!fbs::VerifyGeometrySnapshotBuffer(verifier)) {
    throw FormatError("corrupt or malformed geometry snapshot buffer");
  }

  const fbs::GeometrySnapshot* snapshot = fbs::GetGeometrySnapshot(buffer.data());
  GeometryWorkspace workspace;

  insert_entries(workspace, snapshot->pads(), read_pad);
  insert_entries(workspace, snapshot->vias(), read_via);
  insert_entries(workspace, snapshot->tracks(), read_track);
  insert_entries(workspace, snapshot->copper_pours(), read_copper_pour);
  insert_entries(workspace, snapshot->keepouts(), read_keepout);
  insert_entries(workspace, snapshot->drill_hits(), read_drill_hit);
  insert_entries(workspace, snapshot->mask_openings(), read_mask_opening);
  insert_entries(workspace, snapshot->silkscreen_graphics(), read_silkscreen_graphic);
  insert_entries(workspace, snapshot->footprints(), read_footprint);
  insert_entries(workspace, snapshot->board_outlines(), read_board_outline);

  return workspace;
}

} // namespace pcbir::geometry
