// SPDX-License-Identifier: Apache-2.0
//
// Imports every golden-corpus board (tests/corpus/kicad/, each a real
// file generated by pcbnew scripting, never hand-authored S-expressions
// -- docs/rfcs/0003-kicad-importer-exporter.md's "Golden corpus") and
// checks the result against that board's hand-verified expected.json
// summary. This is the importer's integration-level check, independent
// of the unit-level hand-written S-expression snippets in
// import_test.cpp/import_geometry_test.cpp.
#include "pcbir/core/entity_id.hpp"
#include "pcbir/geometry/arc.hpp"
#include "pcbir/geometry/board_outline.hpp"
#include "pcbir/geometry/contour.hpp"
#include "pcbir/geometry/serialize.hpp"
#include "pcbir/kicad/import.hpp"
#include "pcbir/kicad/import_geometry.hpp"
#include "pcbir/kicad/sexpr.hpp"
#include "pcbir/stackup/layer.hpp"
#include "pcbir/stackup/layer_stack.hpp"
#include "pcbir/stackup/serialize.hpp"

#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <variant>

#include <catch2/catch_test_macros.hpp>

using pcbir::core::EntityId;
using pcbir::kicad::import_board_outline;
using pcbir::kicad::import_stackup;
using pcbir::kicad::parse_sexpr;
using pcbir::stackup::Layer;
using pcbir::stackup::LayerKind;
using pcbir::stackup::LayerStack;
using pcbir::stackup::StackupSnapshot;

using pcbir::geometry::Arc;
using pcbir::geometry::BoardOutline;
using pcbir::geometry::GeometrySnapshot;

namespace {

[[nodiscard]] std::string read_file(const std::string& path) {
  const std::ifstream file(path);
  if (!file) {
    throw std::runtime_error("failed to open corpus file: " + path);
  }
  std::ostringstream buffer;
  buffer << file.rdbuf();
  return buffer.str();
}

[[nodiscard]] std::string corpus_path(const std::string& relative) {
  return std::string(PCBIR_TEST_CORPUS_DIR) + "/kicad/" + relative;
}

int count_copper_layers(const StackupSnapshot& snapshot) {
  int count = 0;
  snapshot.table<Layer>().for_each([&](EntityId, const Layer& layer) {
    if (layer.kind == LayerKind::Copper) {
      ++count;
    }
  });
  return count;
}

int count_silkscreen_layers(const StackupSnapshot& snapshot) {
  int count = 0;
  snapshot.table<Layer>().for_each([&](EntityId, const Layer& layer) {
    if (layer.kind == LayerKind::Silkscreen) {
      ++count;
    }
  });
  return count;
}

int count_arc_spans(const BoardOutline& outline) {
  int count = 0;
  for (const auto& span : outline.outline.outline.spans) {
    if (std::holds_alternative<Arc>(span)) {
      ++count;
    }
  }
  return count;
}

} // namespace

TEST_CASE("rounded-rect-outline corpus board imports the expected stackup layer counts",
          "[kicad][corpus]") {
  const pcbir::kicad::SExpr root =
      parse_sexpr(read_file(corpus_path("rounded-rect-outline/board.kicad_pcb")));
  const StackupSnapshot stackup = import_stackup(root);

  // Per tests/corpus/kicad/rounded-rect-outline/expected.json.
  REQUIRE(count_copper_layers(stackup) == 2);
  REQUIRE(count_silkscreen_layers(stackup) == 2);
  REQUIRE(stackup.table<LayerStack>().size() == 1);
}

TEST_CASE("rounded-rect-outline corpus board's LayerStack has both Copper layers",
          "[kicad][corpus]") {
  const pcbir::kicad::SExpr root =
      parse_sexpr(read_file(corpus_path("rounded-rect-outline/board.kicad_pcb")));
  const StackupSnapshot stackup = import_stackup(root);

  const LayerStack* stack = nullptr;
  stackup.table<LayerStack>().for_each(
      [&](EntityId, const LayerStack& candidate) { stack = &candidate; });
  REQUIRE(stack != nullptr);
  REQUIRE(stack->layers.size() == 2);
}

TEST_CASE("rounded-rect-outline corpus board assembles its 8 authored edges into one closed "
          "outline",
          "[kicad][corpus]") {
  const pcbir::kicad::SExpr root =
      parse_sexpr(read_file(corpus_path("rounded-rect-outline/board.kicad_pcb")));
  const StackupSnapshot stackup = import_stackup(root);
  const GeometrySnapshot geometry = import_board_outline(root, stackup);

  // Per tests/corpus/kicad/rounded-rect-outline/expected.json: 4 gr_line +
  // 4 gr_arc, authored out of loop order, assemble into exactly one
  // closed 8-span loop.
  REQUIRE(geometry.table<BoardOutline>().size() == 1);

  const BoardOutline* outline = nullptr;
  geometry.table<BoardOutline>().for_each(
      [&](EntityId, const BoardOutline& candidate) { outline = &candidate; });
  REQUIRE(outline != nullptr);
  REQUIRE(outline->outline.outline.spans.size() == 8);
  REQUIRE(count_arc_spans(*outline) == 4);
}

TEST_CASE("rounded-rect-outline corpus board's outline is counterclockwise and every arc is "
          "geometrically valid",
          "[kicad][corpus]") {
  const pcbir::kicad::SExpr root =
      parse_sexpr(read_file(corpus_path("rounded-rect-outline/board.kicad_pcb")));
  const StackupSnapshot stackup = import_stackup(root);
  const GeometrySnapshot geometry = import_board_outline(root, stackup);

  const BoardOutline* outline = nullptr;
  geometry.table<BoardOutline>().for_each(
      [&](EntityId, const BoardOutline& candidate) { outline = &candidate; });
  REQUIRE(outline != nullptr);
  REQUIRE(pcbir::geometry::orientation(outline->outline.outline) ==
          pcbir::geometry::Orientation::CounterClockwise);

  bool every_arc_valid = true;
  for (const auto& span : outline->outline.outline.spans) {
    if (const auto* arc = std::get_if<Arc>(&span); arc != nullptr && !arc->is_valid()) {
      every_arc_valid = false;
    }
  }
  REQUIRE(every_arc_valid);
}
