// SPDX-License-Identifier: Apache-2.0
#include "pcbir/stackup/serialize.hpp"

#include "pcbir/core/entity_id.hpp"
#include "pcbir/stackup/impedance_profile.hpp"
#include "pcbir/stackup/layer.hpp"
#include "pcbir/stackup/layer_stack.hpp"
#include "pcbir/stackup/material.hpp"

// The FlatBuffers runtime library's own convention (every flatc-generated
// header includes exactly this), even though its symbols are physically
// declared in finer-grained sub-headers that misc-include-cleaner would
// rather see named individually.
// NOLINTNEXTLINE(misc-include-cleaner)
#include <flatbuffers/flatbuffers.h>

#include <cstdint>
#include <span>
#include <vector>

// Generated by build_flatbuffers() from schemas/stackup.fbs (src/CMakeLists.txt).
#include "stackup_generated.h"

namespace pcbir::stackup {

namespace {

namespace fbs = pcbir::stackup::fbs;

// NOLINTNEXTLINE(misc-include-cleaner)
flatbuffers::Offset<fbs::Material> write_material(flatbuffers::FlatBufferBuilder& builder,
                                                  const Material& material) {
  return fbs::CreateMaterialDirect(
      builder, material.name.c_str(), material.dielectric_constant_e6, material.loss_tangent_e6);
}

Material read_material(const fbs::Material* material) {
  return Material{.name = material->name() != nullptr ? material->name()->str() : std::string(),
                  .dielectric_constant_e6 = material->dielectric_constant_e6(),
                  .loss_tangent_e6 = material->loss_tangent_e6()};
}

fbs::LayerKind write_layer_kind(LayerKind kind) {
  return kind == LayerKind::Copper ? fbs::LayerKind_Copper : fbs::LayerKind_Dielectric;
}

LayerKind read_layer_kind(fbs::LayerKind kind) {
  return kind == fbs::LayerKind_Copper ? LayerKind::Copper : LayerKind::Dielectric;
}

flatbuffers::Offset<fbs::Layer> write_layer(flatbuffers::FlatBufferBuilder& builder,
                                            const Layer& layer) {
  return fbs::CreateLayerDirect(builder,
                                layer.name.c_str(),
                                write_layer_kind(layer.kind),
                                layer.thickness_nm,
                                layer.roughness_nm,
                                layer.material.value());
}

Layer read_layer(const fbs::Layer* layer) {
  return Layer{.name = layer->name() != nullptr ? layer->name()->str() : std::string(),
               .kind = read_layer_kind(layer->kind()),
               .thickness_nm = layer->thickness_nm(),
               .roughness_nm = layer->roughness_nm(),
               .material = core::EntityId{layer->material()}};
}

flatbuffers::Offset<fbs::LayerStack> write_layer_stack(flatbuffers::FlatBufferBuilder& builder,
                                                       const LayerStack& stack) {
  std::vector<uint64_t> layers;
  layers.reserve(stack.layers.size());
  for (const core::EntityId& layer : stack.layers) {
    layers.push_back(layer.value());
  }
  return fbs::CreateLayerStackDirect(builder, stack.name.c_str(), &layers);
}

LayerStack read_layer_stack(const fbs::LayerStack* stack) {
  LayerStack result{.name = stack->name() != nullptr ? stack->name()->str() : std::string(),
                    .layers = {}};
  if (const auto* layers = stack->layers()) {
    result.layers.reserve(layers->size());
    for (const uint64_t layer : *layers) {
      result.layers.emplace_back(layer);
    }
  }
  return result;
}

flatbuffers::Offset<fbs::ImpedanceProfile>
write_impedance_profile(flatbuffers::FlatBufferBuilder& builder, const ImpedanceProfile& profile) {
  return fbs::CreateImpedanceProfileDirect(
      builder, profile.class_name.c_str(), profile.target_ohm_e6, profile.actual_ohm_e6);
}

ImpedanceProfile read_impedance_profile(const fbs::ImpedanceProfile* profile) {
  return ImpedanceProfile{
      .class_name = profile->class_name() != nullptr ? profile->class_name()->str() : std::string(),
      .target_ohm_e6 = profile->target_ohm_e6(),
      .actual_ohm_e6 = profile->actual_ohm_e6()};
}

} // namespace

std::vector<uint8_t> serialize(const StackupSnapshot& snapshot) {
  flatbuffers::FlatBufferBuilder builder;

  std::vector<flatbuffers::Offset<fbs::MaterialEntry>> materials;
  snapshot.table<Material>().for_each([&](core::EntityId id, const Material& material) {
    materials.push_back(
        fbs::CreateMaterialEntry(builder, id.value(), write_material(builder, material)));
  });

  std::vector<flatbuffers::Offset<fbs::LayerEntry>> layers;
  snapshot.table<Layer>().for_each([&](core::EntityId id, const Layer& layer) {
    layers.push_back(fbs::CreateLayerEntry(builder, id.value(), write_layer(builder, layer)));
  });

  std::vector<flatbuffers::Offset<fbs::LayerStackEntry>> layer_stacks;
  snapshot.table<LayerStack>().for_each([&](core::EntityId id, const LayerStack& stack) {
    layer_stacks.push_back(
        fbs::CreateLayerStackEntry(builder, id.value(), write_layer_stack(builder, stack)));
  });

  std::vector<flatbuffers::Offset<fbs::ImpedanceProfileEntry>> impedance_profiles;
  snapshot.table<ImpedanceProfile>().for_each(
      [&](core::EntityId id, const ImpedanceProfile& profile) {
        impedance_profiles.push_back(fbs::CreateImpedanceProfileEntry(
            builder, id.value(), write_impedance_profile(builder, profile)));
      });

  const flatbuffers::Offset<fbs::StackupSnapshot> root = fbs::CreateStackupSnapshotDirect(
      builder, &materials, &layers, &layer_stacks, &impedance_profiles);
  builder.Finish(root);

  const uint8_t* buffer_ptr = builder.GetBufferPointer();
  // GetBufferPointer()/GetSize() are a guaranteed-consistent pair from the
  // FlatBufferBuilder's own contract.
  // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-pointer-arithmetic)
  return {buffer_ptr, buffer_ptr + builder.GetSize()};
}

StackupWorkspace deserialize_stackup(std::span<const uint8_t> buffer) {
  const fbs::StackupSnapshot* snapshot = fbs::GetStackupSnapshot(buffer.data());
  StackupWorkspace workspace;

  if (const auto* materials = snapshot->materials()) {
    for (const fbs::MaterialEntry* entry : *materials) {
      workspace.insert_with_id(read_material(entry->value()), core::EntityId{entry->id()});
    }
  }
  if (const auto* layers = snapshot->layers()) {
    for (const fbs::LayerEntry* entry : *layers) {
      workspace.insert_with_id(read_layer(entry->value()), core::EntityId{entry->id()});
    }
  }
  if (const auto* layer_stacks = snapshot->layer_stacks()) {
    for (const fbs::LayerStackEntry* entry : *layer_stacks) {
      workspace.insert_with_id(read_layer_stack(entry->value()), core::EntityId{entry->id()});
    }
  }
  if (const auto* impedance_profiles = snapshot->impedance_profiles()) {
    for (const fbs::ImpedanceProfileEntry* entry : *impedance_profiles) {
      workspace.insert_with_id(read_impedance_profile(entry->value()), core::EntityId{entry->id()});
    }
  }

  return workspace;
}

} // namespace pcbir::stackup
